if(NOT DEFINED MLC_OPT OR NOT DEFINED FILECHECK_EXE OR NOT DEFINED INPUT_FILE OR
   NOT DEFINED TMP_FILE)
  message(FATAL_ERROR "Missing required -D variables for FileCheck runner.")
endif()

execute_process(
  COMMAND ${MLC_OPT} --mlc-div-to-reciprocal-mul ${INPUT_FILE}
  RESULT_VARIABLE MLC_OPT_RESULT
  OUTPUT_VARIABLE TRANSFORMED_IR
  ERROR_VARIABLE MLC_OPT_STDERR
)

if(NOT MLC_OPT_RESULT EQUAL 0)
  message(FATAL_ERROR "mlc-opt failed:\n${MLC_OPT_STDERR}")
endif()

file(WRITE ${TMP_FILE} "${TRANSFORMED_IR}")

execute_process(
  COMMAND ${FILECHECK_EXE} ${INPUT_FILE}
  INPUT_FILE ${TMP_FILE}
  RESULT_VARIABLE FILECHECK_RESULT
  OUTPUT_VARIABLE FILECHECK_STDOUT
  ERROR_VARIABLE FILECHECK_STDERR
)

if(NOT FILECHECK_RESULT EQUAL 0)
  message(FATAL_ERROR "FileCheck failed.\n${FILECHECK_STDOUT}\n${FILECHECK_STDERR}")
endif()
